### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mrrobotisback** [hodongnhut/magento2-payment-discount#1]
Hi,

like in your screen of readme on checkout, the discount is not applied to totals calculation.
Why ?

**Comment by hodongnhut** [comment]
Which the magento version do you have? you can  ping me by skype: hodongnhut
I can support for this one
Thank

**Comment by mrrobotisback** [comment]
I use magento 2.4.5 p1

**Comment by mrrobotisback** [comment]
Like in your screenshot: 
![image](https://github.com/hodongnhut/magento2-payment-discount/assets/23551496/14124c80-6136-438b-be20-1b8b34da7f46)

The discount is only viewed but not applied in grand total.

The right grand total is 2069

**Comment by hodongnhut** [comment]
hi @mrrobotisback
I apply for 2.3.7 ver. I saw you use different 
I can support you for updated . plz contact me with cheap price 
skype: hodongnhut
Thank you

**Comment by mrrobotisback** [comment]
Hi @hodongnhut ,

I have already developed a custom module to develop this specification, thanks anyway for your availability.
